enyo.depends(
    "$lib/onyx",
    "$lib/layout",
    "NumberPad.css",
    "NumberPad.js",
    "Envelope.css",
    "Envelope.js",
    "BuyPopup.css",
    "BuyPopup.js",
    "Envelopes.js",
    "SparsamApp.js"
);
