enyo.depends(
    "$lib/onyx",
    "$lib/layout",
    "Envelope.css",
    "Envelope.js",
    "Envelopes.js",
    "SpendHistory.js",
    "SpendHistoryColumn.js",
    "SpendHistoryItem.js",
    "SpendHistoryItem.css",
    "SpendNow.js",
    "SpendNow.css",
    "SparsamApp.js",
    "SparsamApp.css",
    "requests.js"
);
